POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpIiwiaWQiOiI2MGI3NWQ1Mjk3ODk4OTk3MmZlOWUxMzMiLCJpYXQiOjE2MjM2NTg2Njd9.Ex0_pDKicMGTuskydEzWKDl1mI7ZqjgAx2W77gNarOE


{
      "_id": "5a422b3a1b54a676234d12f9",
      "title": "Canonical string reduction",
      "author": "Edsger W. Dijkstra",
      "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
      "likes": 12,
      "__v": 0
    }